# Generated by Django 2.2.5 on 2019-12-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CarID', models.CharField(max_length=30)),
                ('Latitude', models.CharField(max_length=30)),
                ('Longitude', models.CharField(max_length=30)),
            ],
        ),
    ]
